# Generated by Django 4.2.6 on 2023-11-10 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CountIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.CharField(max_length=20)),
                (
                    "optional",
                    models.BooleanField(
                        db_comment="Ингредиент, необязательный в рецепте (н-р, для подачи)",
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "always_available",
                    models.BooleanField(
                        db_comment="Ингредиент, который всегда есть дома (н-р, соль, перец и т.п.).",
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        db_comment="Время приготовления в минутах.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("description", models.TextField(db_comment="Рецепт приготовления.")),
                ("image", models.CharField(blank=True, max_length=300, null=True)),
                ("categories", models.ManyToManyField(to="api.category")),
                (
                    "ingredients",
                    models.ManyToManyField(
                        through="api.CountIngredients", to="api.ingredient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="countingredients",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="count_ingredient",
                to="api.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="countingredients",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
            ),
        ),
    ]
