version: "3.9"

services:

  my_cookbook:
    build: .
    container_name: my_cookbook
    env_file:
      - .env
    volumes:
      - ./cookbook:/usr/share/my_cookbook/cookbook
    ports:
      - 8000:8000
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
